<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT3tnp0u\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT3tnp0u/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT3tnp0u.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT3tnp0u\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT3tnp0u\appProdProjectContainer(array(
    'container.build_hash' => 'T3tnp0u',
    'container.build_id' => 'ba75c17b',
    'container.build_time' => 1528279407,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT3tnp0u');
