<?php

namespace biblioBundle\Repository;

/**
 * EmprunteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmprunteurRepository extends \Doctrine\ORM\EntityRepository
{
}
