<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfuukgh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfuukgh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJfuukgh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJfuukgh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJfuukgh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jfuukgh',
    'container.build_id' => '77993bb5',
    'container.build_time' => 1528875817,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJfuukgh');
