<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdfgyma\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdfgyma/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRdfgyma.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRdfgyma\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRdfgyma\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rdfgyma',
    'container.build_id' => '1ed8903f',
    'container.build_time' => 1528467380,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdfgyma');
